[package]
name = "poisson"
version = "0.4.0"
authors = ["WaDelma <>"]
description = "Poisson-disk distribution generator."
repository = "https://github.com/WaDelma/poisson"
documentation = "https://WaDelma.github.io/poisson/"
readme = "README.md"
keywords = [ "poisson" ]
license = "MIT"

[dependencies]
rand = "0.3.8"
nalgebra = "0.2.17"
num = "0.1.25"
lazy_static = "0.1.11"
