[package]
name = "poisson"
version = "0.3.0"
authors = ["WaDelma <>"]
description = "Poisson-disk distribution generator."
repository = "https://github.com/WaDelma/poisson"
documentation = "https://WaDelma.github.io/poisson/"
readme = "README.md"
keywords = [ "poisson" ]
license = "MIT"

[dependencies]
rand = "0.3.8"
nalgebra = "0.2.15"
num = "0.1.24"
debug_unreachable = "0.0.5"
